In [2]:
import numpy as np
np.arange(0,10,0.55)

array([0.  , 0.55, 1.1 , 1.65, 2.2 , 2.75, 3.3 , 3.85, 4.4 , 4.95, 5.5 ,
       6.05, 6.6 , 7.15, 7.7 , 8.25, 8.8 , 9.35, 9.9 ])

In [4]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
np.random.rand(3,3)

array([[0.3023166 , 0.39337055, 0.27498893],
       [0.28026534, 0.17524077, 0.83553241],
       [0.28233387, 0.97551004, 0.29914394]])

In [17]:
np.random.randn(3,5)

array([[ 2.12417577e+00, -1.40945540e+00,  4.26483591e-01,
        -2.92626267e-01,  2.48124481e+00],
       [-1.63991749e-01,  5.01018097e-01, -6.02917248e-01,
         1.43742670e+00, -1.48015024e+00],
       [ 2.17582943e+00,  2.21502897e+00,  1.30347967e-01,
        -4.80307194e-01, -6.83976310e-04]])

In [21]:
np.random.randint(1,100,10)

array([14, 72, 16, 74,  7, 85, 15, 68, 48, 83])

In [40]:
arr=np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [43]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [36]:
arr=np.random.randn(10,10)
# arr.reshape(5,5)
# ValueError: cannot reshape array of size 100 into shape (5,5)
arr.reshape(10,10)


array([[ 0.41343488, -0.76329457,  0.85543493, -0.51428116, -0.6280981 ,
        -0.73676133,  0.22624667, -0.49072623,  1.52319668, -0.19808535],
       [ 0.32512534, -1.41025284, -0.59709034,  1.62303368,  0.70087853,
         0.28091535, -0.69454125,  0.35920267,  0.38580733, -0.40152071],
       [ 0.25441196, -0.33106732,  0.34776914,  2.23085901,  0.85297185,
        -0.84409732, -1.94789499,  0.64633821,  0.20844371, -0.94267942],
       [-1.2737396 ,  1.32650001, -1.33919689,  0.29378244, -0.34865006,
        -1.03589261, -0.28943039,  1.45776194,  0.9459262 , -1.37296358],
       [ 1.04792799,  1.94324415,  1.64046293, -1.1890878 , -0.53451784,
         0.03679685,  0.89321836,  0.66508769,  0.40553857,  0.04928981],
       [-0.14018018,  0.03838015, -1.16215282,  0.27074199, -0.57918778,
         1.18685125, -1.3742473 , -0.6887175 ,  1.18992782, -0.03605723],
       [-0.96046731,  0.21903089,  1.17891212,  0.64561179, -0.57833225,
        -1.01867425, -1.43276511,  1.0681959 

In [59]:
arr=np.arange(1,10)
newarr=arr
newarr[1:5]=99
arr[5:10]=100
copy_arr=arr.copy()
copy_arr[:]=0
copy_arr
arr

array([  1,  99,  99,  99,  99, 100, 100, 100, 100])

In [101]:
arr=np.array([[1,2,3],[5,3,4],[4,5,6]])
print(arr)
arr[0:2,0:1]

[[1 2 3]
 [5 3 4]
 [4 5 6]]


array([[1],
       [5]])

In [112]:
arr=np.arange(1,10)
bolean=arr>5
# bolean array([False, False, False, False, False,  True,  True,  True,  True])
# arr[bolean] --> array([6, 7, 8, 9])
# arr[arr<5]-->array([1, 2, 3, 4])


array([1, 2, 3, 4])

In [121]:
arr=np.arange(50).reshape(5,10)
print(arr)
middle=arr[1:4,4:7]
middle


[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


array([[14, 15, 16],
       [24, 25, 26],
       [34, 35, 36]])

In [124]:
test = np.array([[4,7], [2,6]])
test

array([[4, 7],
       [2, 6]])

In [123]:
np.linalg.inv(test)

array([[ 0.6, -0.7],
       [-0.2,  0.4]])